./1-helm-install-conjur.sh
./2-get-conjur-token-whoami.sh
./3-set-conjur-k8s-policy.sh
./4-set-conjur-k8s-ca.sh
./5-helm-install-cluster-prep.sh
./6-helm-install-namespace-prep.sh
./7-set-conjour-policy-app.sh
./8-helm-install-app-demo.sh
./9-bootstrap-install-flux.sh
