apiVersion: v1
kind: Secret
metadata:
  name: github-cred
type: Opaque
data:
  token: ZW1wdHkK
stringData:
  conjur-map: |-   
    token: demo-app/github_cred 

---
apiVersion: v1
kind: Secret
metadata:
  name: slack-botduty-webhook
type: Opaque
data:
  token: ZW1wdHkK
stringData:
  conjur-map: |-   
    token: demo-app/slack_botduty_webhook

---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiIwMDc5YTMxZS02OGRkLTQ2NWUtOTQyMi0yYzVmZDIxMmYzMDAiLCJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImF1dGgiOiJkWE5sY2pvd01EYzVZVE14WlMwMk9HUmtMVFEyTldVdE9UUXlNaTB5WXpWbVpESXhNbVl6TURBPSJ9fX0=
stringData:
  conjur-map: |-   
    .dockerconfigjson: demo-app/dockerhub_cred