apiVersion: v1
kind: Secret
metadata:
  name: github-cred
type: Opaque
data:
  token: ZW1wdHkK
stringData:
  conjur-map: |-   
    token: demo-app/github_cred 

---
apiVersion: v1
kind: Secret
metadata:
  name: slack-botduty-webhook
type: Opaque
data:
  token: ZW1wdHkK
stringData:
  conjur-map: |-   
    token: demo-app/slack_botduty_webhook

---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e2F1dGhzOntodHRwczovL2luZGV4LmRvY2tlci5pby92MS86dXNlcm5hbWU6dXNlcn19IHthdXRoczp7aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOnBhc3N3b3JkOnB3ZH19IHthdXRoczp7aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOmVtYWlsOnVzZXJAZG9tYWluLmNvbX19IHthdXRoczp7aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOmF1dGg6ZFhObGNqb3hPRGM1WVRNeFpTMDJPR1JrTFRRMk5XVXRPVFF5TWkweVl6Vm1aREl4TW1Zek1EQUt9fQo=
stringData:
  conjur-map: |-   
    .dockerconfigjson: demo-app/dockerhub_cred