apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}-conjur-k8s-secret-provider
  labels:
    app: himeji
    zone: prod
    version: v1
spec:
  serviceAccountName: himeji-serviceaccount
  terminationGracePeriodSeconds: 1
  hostAliases:
  - ip: {{ .Values.conjur_ingress.ip }}
    hostnames:
    - "conjur.myorg.com"
  restartPolicy: Never
  containers:
  - image: {{ .Values.image.conjur_sidecar.repository }}:{{ .Values.image.conjur_sidecar.tag }}
    imagePullPolicy: Always
    name: cyberark-secrets-provider-for-k8s
    env:
      - name: DEBUG
        value: "true"
      - name: CONJUR_AUTHN_LOGIN
        value: host/{{ .Values.conjur_host.id }}
      - name: CONTAINER_MODE
        value: application
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K8S_SECRETS
        value: dockerhub-cred 
      - name: SECRETS_DESTINATION
        value: k8s_secrets    
    envFrom:
      - configMapRef:
          name: conjur-connect
