apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    name: himeji-app-serviceaccount
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access 