image:
  himeji_app:
    repository: davidlang/himeji-private
    #tag: "v22.2.23.2"
    tag: "v22.3.6"
  conjur_sidecar:
    repository: cyberark/secrets-provider-for-k8s
    tag: "latest"
conjur_ingress:
  ip: "1.1.1.1"
conjur_host:
  id: "himeji-app"
replicaCount: 2
