apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}-conjur-k8s-secret-provider
  labels:
    app: himeji
spec:
  selector:
    matchLabels:
      app: himeji
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: himeji
    spec:
      serviceAccountName: himeji-serviceaccount
      terminationGracePeriodSeconds: 1
      hostAliases:
      - ip: {{ .Values.conjur_ingress.ip }}
        hostnames:
        - "conjur.myorg.com"
      containers:
      - image: {{ .Values.image.conjur_sidecar.repository }}:{{ .Values.image.conjur_sidecar.tag }}
        imagePullPolicy: Always
        name: cyberark-secrets-provider-for-k8s
        env:
          - name: DEBUG
            value: "true"
          - name: CONJUR_AUTHN_LOGIN
            value: host/himeji-app
          - name: CONTAINER_MODE
            value: application
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
